---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: sikulix
    run_list:
      - recipe[sikulix_test::default]
    attributes:
      java:
        jdk_version: '7'
      sikulix:
        setup: {
          ide_jython: false,
          ide_jruby: false,
          java_api: true,
          tesseract_ocr: false,
          system_all: false,
          system_windows: false,
          system_mac: false,
          system_linux: false,
        }
