---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
#  - name: ubuntu-12.04
  - name: ubuntu-14.04
#  - name: ubuntu-14.10

suites:
  - name: sikulix
    run_list:
      - recipe[sikulix_test::default]
    attributes:
      {
        "java": {
          "jdk_version": "7"
        },
        "sikulix": {
          "setup": {
            "ide_jython": true,
            "ide_jruby": true,
            "ide_jruby_addons": true,
            "java_api": true,
            "tesseract_ocr": true,
            "system_all": true,
            "remoteserver": true
          }
        }
      }
