---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      box: boxcutter/ubuntu1404-desktop
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[sikulix_test::default]
    attributes:
      sikulix:
        username: vagrant
        setup: {
          ide_jython: true,
          ide_jruby: true,
          java_api: true,
          tesseract_ocr: true,
          system_all: false,
          buildv: false,
          notest: false,
          clean: false
        }
