---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: sikulix
    run_list:
      - recipe[sikulix_test::default]
    attributes:
      java:
        jdk_version: '7'
      sikulix:
        setup: {
          ide_jython: true,
          ide_jruby: true,
          java_api: true,
          tesseract_ocr: true,
          system_all: false,
          system_windows: true,
          system_mac: true,
          system_linux: true,
          buildv: true,
          notest: true,
          clean: false
        }
